GET http://localhost:3001/checklists

###


POST http://localhost:3001/checklist/new
Content-Type: application/json

{
    "text":"Do homework 1"
}

###

DELETE http://localhost:3001/checklist/delete/636586c5d25472842e3ef610


###

PUT http://localhost:3001/checklist/complete/63658f57d25809bda87368a8