GET http://localhost:3001/checklists

###


POST http://localhost:3001/checklist/new
Content-Type: application/json

{
    "text":"Do homework 1"
}

###

DELETE http://localhost:3001/checklist/delete/6365a4c07b7a5bd3ed2b9fcc


###

PUT http://localhost:3001/checklist/complete/63658f57d25809bda87368a8